# Generated by Django 3.1.5 on 2021-01-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Encuesta')),
                ('description', models.TextField(verbose_name='Descripción de la encuesta')),
                ('category_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.categoriaencuesta', verbose_name='Categoria de la Encuesta')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción de la pregunta')),
                ('question_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta', verbose_name='Categoria de la Encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción de la alternativa')),
                ('alternative_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta', verbose_name='Categoria de la Encuesta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
    ]
