# Generated by Django 3.1.5 on 2021-01-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='category_survey',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='categories',
            field=models.ManyToManyField(to='encuesta.CategoriaEncuesta'),
        ),
    ]
