# Generated by Django 3.1.5 on 2021-01-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20210119_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativas',
            name='alternative_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.preguntas', verbose_name='Alternativa de la pregunta'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='question_survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta', verbose_name='Pregunta de la encuesta'),
        ),
    ]
