# Generated by Django 3.1.5 on 2021-01-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_auto_20210119_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='question_survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuesta.encuesta', verbose_name='Pregunta de la encuesta'),
        ),
    ]
