# Generated by Django 3.1.5 on 2021-01-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20210119_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativas',
            name='alternative_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='encuesta.preguntas', verbose_name='Alternativa de la pregunta'),
        ),
    ]
